inherit_from: ~/.rubocop.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - config/initializers/filter_parameter_logging.rb

Layout/LineLength:
  Exclude:
    - config/initializers/devise.rb


# rubocop-rails

Style/FrozenStringLiteralComment:
  Exclude:
    - db/migrate/**/*


# rubocop-rspec

RSpec/ImplicitExpect:
  EnforcedStyle: should

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
